{ kernel, pkgs, ... }:
kernel.override {
	extraConfig = ''
#
# Automatically generated file; DO NOT EDIT.
# Linux/x86 5.15.12 Kernel Configuration
#
IRQ_WORK y
BUILDTIME_TABLE_SORT y
THREAD_INFO_IN_TASK y

#
# General setup
#
INIT_ENV_ARG_LIMIT 32
COMPILE_TEST n
WERROR n
LOCALVERSION ""
LOCALVERSION_AUTO n
BUILD_SALT ""
HAVE_KERNEL_GZIP y
HAVE_KERNEL_BZIP2 y
HAVE_KERNEL_LZMA y
HAVE_KERNEL_XZ y
HAVE_KERNEL_LZO y
HAVE_KERNEL_LZ4 y
HAVE_KERNEL_ZSTD y
KERNEL_GZIP y
KERNEL_BZIP2 n
KERNEL_LZMA n
KERNEL_XZ n
KERNEL_LZO n
KERNEL_LZ4 n
KERNEL_ZSTD n
DEFAULT_INIT ""
DEFAULT_HOSTNAME "cloud-hypervisor"
SWAP y
SYSVIPC y
SYSVIPC_SYSCTL y
POSIX_MQUEUE y
POSIX_MQUEUE_SYSCTL y
WATCH_QUEUE n
CROSS_MEMORY_ATTACH y
USELIB n
AUDIT y
HAVE_ARCH_AUDITSYSCALL y
AUDITSYSCALL y

#
# IRQ subsystem
#
GENERIC_IRQ_PROBE y
GENERIC_IRQ_SHOW y
GENERIC_IRQ_EFFECTIVE_AFF_MASK y
GENERIC_PENDING_IRQ y
GENERIC_IRQ_MIGRATION y
HARDIRQS_SW_RESEND y
IRQ_DOMAIN y
IRQ_DOMAIN_HIERARCHY y
GENERIC_MSI_IRQ y
GENERIC_MSI_IRQ_DOMAIN y
IRQ_MSI_IOMMU y
GENERIC_IRQ_MATRIX_ALLOCATOR y
GENERIC_IRQ_RESERVATION_MODE y
IRQ_FORCED_THREADING y
SPARSE_IRQ y
GENERIC_IRQ_DEBUGFS n
# end of IRQ subsystem

CLOCKSOURCE_WATCHDOG y
ARCH_CLOCKSOURCE_INIT y
CLOCKSOURCE_VALIDATE_LAST_CYCLE y
GENERIC_TIME_VSYSCALL y
GENERIC_CLOCKEVENTS y
GENERIC_CLOCKEVENTS_BROADCAST y
GENERIC_CLOCKEVENTS_MIN_ADJUST y
GENERIC_CMOS_UPDATE y
HAVE_POSIX_CPU_TIMERS_TASK_WORK y
POSIX_CPU_TIMERS_TASK_WORK y

#
# Timers subsystem
#
TICK_ONESHOT y
NO_HZ_COMMON y
HZ_PERIODIC n
NO_HZ_IDLE y
NO_HZ_FULL n
NO_HZ y
HIGH_RES_TIMERS y
# end of Timers subsystem

BPF y
HAVE_EBPF_JIT y
ARCH_WANT_DEFAULT_BPF_JIT y

#
# BPF subsystem
#
BPF_SYSCALL y
BPF_UNPRIV_DEFAULT_OFF n
BPF_PRELOAD n
# end of BPF subsystem

PREEMPT_NONE y
PREEMPT_VOLUNTARY n
PREEMPT n
SCHED_CORE n

#
# CPU/Task time and stats accounting
#
TICK_CPU_ACCOUNTING y
VIRT_CPU_ACCOUNTING_GEN n
IRQ_TIME_ACCOUNTING n
HAVE_SCHED_AVG_IRQ y
BSD_PROCESS_ACCT y
BSD_PROCESS_ACCT_V3 y
TASKSTATS y
TASK_DELAY_ACCT y
TASK_XACCT y
TASK_IO_ACCOUNTING y
PSI n
# end of CPU/Task time and stats accounting

CPU_ISOLATION y

#
# RCU Subsystem
#
TREE_RCU y
RCU_EXPERT n
SRCU y
TREE_SRCU y
TASKS_RCU_GENERIC y
TASKS_TRACE_RCU y
RCU_STALL_COMMON y
RCU_NEED_SEGCBLIST y
# end of RCU Subsystem

BUILD_BIN2C y
IKCONFIG n
IKHEADERS n
LOG_BUF_SHIFT 21
LOG_CPU_MAX_BUF_SHIFT 12
PRINTK_SAFE_LOG_BUF_SHIFT 13
PRINTK_INDEX n
HAVE_UNSTABLE_SCHED_CLOCK y

#
# Scheduler features
#
UCLAMP_TASK n
# end of Scheduler features

ARCH_SUPPORTS_NUMA_BALANCING y
ARCH_WANT_BATCHED_UNMAP_TLB_FLUSH y
CC_HAS_INT128 y
ARCH_SUPPORTS_INT128 y
NUMA_BALANCING y
NUMA_BALANCING_DEFAULT_ENABLED n
CGROUPS y
PAGE_COUNTER y
MEMCG y
MEMCG_SWAP y
MEMCG_KMEM y
BLK_CGROUP y
CGROUP_WRITEBACK y
CGROUP_SCHED y
FAIR_GROUP_SCHED y
CFS_BANDWIDTH y
RT_GROUP_SCHED y
CGROUP_PIDS y
CGROUP_RDMA n
CGROUP_FREEZER y
CGROUP_HUGETLB y
CPUSETS y
PROC_PID_CPUSET y
CGROUP_DEVICE y
CGROUP_CPUACCT y
CGROUP_PERF y
CGROUP_BPF y
CGROUP_MISC n
CGROUP_DEBUG n
SOCK_CGROUP_DATA y
NAMESPACES y
UTS_NS y
TIME_NS n
IPC_NS y
USER_NS y
PID_NS y
NET_NS y
CHECKPOINT_RESTORE n
SCHED_AUTOGROUP y
SYSFS_DEPRECATED n
RELAY y
BLK_DEV_INITRD y
INITRAMFS_SOURCE ""
RD_GZIP y
RD_BZIP2 y
RD_LZMA y
RD_XZ y
RD_LZO y
RD_LZ4 y
RD_ZSTD y
BOOT_CONFIG n
CC_OPTIMIZE_FOR_PERFORMANCE y
CC_OPTIMIZE_FOR_SIZE n
LD_ORPHAN_WARN y
SYSCTL y
SYSCTL_EXCEPTION_TRACE y
HAVE_PCSPKR_PLATFORM y
EXPERT y
MULTIUSER y
SGETMASK_SYSCALL y
SYSFS_SYSCALL y
FHANDLE y
POSIX_TIMERS y
PRINTK y
BUG y
ELF_CORE y
PCSPKR_PLATFORM y
BASE_FULL y
FUTEX y
FUTEX_PI y
EPOLL y
SIGNALFD y
TIMERFD y
EVENTFD y
SHMEM y
AIO y
IO_URING y
ADVISE_SYSCALLS y
HAVE_ARCH_USERFAULTFD_WP y
HAVE_ARCH_USERFAULTFD_MINOR y
MEMBARRIER y
KALLSYMS y
KALLSYMS_ALL n
KALLSYMS_ABSOLUTE_PERCPU y
KALLSYMS_BASE_RELATIVE y
USERFAULTFD y
ARCH_HAS_MEMBARRIER_SYNC_CORE y
KCMP n
RSEQ y
DEBUG_RSEQ n
EMBEDDED n
HAVE_PERF_EVENTS y
PC104 n

#
# Kernel Performance Events And Counters
#
PERF_EVENTS y
DEBUG_PERF_USE_VMALLOC n
# end of Kernel Performance Events And Counters

VM_EVENT_COUNTERS y
SLUB_DEBUG y
COMPAT_BRK n
SLAB n
SLUB y
SLOB n
SLAB_MERGE_DEFAULT y
SLAB_FREELIST_RANDOM n
SLAB_FREELIST_HARDENED y
SHUFFLE_PAGE_ALLOCATOR n
SLUB_CPU_PARTIAL y
PROFILING n
# end of General setup

64BIT y
X86_64 y
X86 y
INSTRUCTION_DECODER y
OUTPUT_FORMAT "elf64-x86-64"
LOCKDEP_SUPPORT y
STACKTRACE_SUPPORT y
MMU y
ARCH_MMAP_RND_BITS_MIN 28
ARCH_MMAP_RND_BITS_MAX 32
ARCH_MMAP_RND_COMPAT_BITS_MIN 8
ARCH_MMAP_RND_COMPAT_BITS_MAX 16
GENERIC_BUG y
GENERIC_BUG_RELATIVE_POINTERS y
GENERIC_CALIBRATE_DELAY y
ARCH_HAS_CPU_RELAX y
ARCH_HAS_FILTER_PGPROT y
HAVE_SETUP_PER_CPU_AREA y
NEED_PER_CPU_EMBED_FIRST_CHUNK y
NEED_PER_CPU_PAGE_FIRST_CHUNK y
ARCH_HIBERNATION_POSSIBLE y
ARCH_NR_GPIO 1024
ARCH_SUSPEND_POSSIBLE y
ARCH_WANT_GENERAL_HUGETLB y
AUDIT_ARCH y
X86_64_SMP y
ARCH_SUPPORTS_UPROBES y
FIX_EARLYCON_MEM y
DYNAMIC_PHYSICAL_MASK y
PGTABLE_LEVELS 5
CC_HAS_SANE_STACKPROTECTOR y

#
# Processor type and features
#
SMP y
X86_FEATURE_NAMES y
X86_X2APIC y
X86_MPPARSE y
GOLDFISH n
RETPOLINE y
X86_CPU_RESCTRL n
X86_EXTENDED_PLATFORM n
X86_INTEL_LPSS n
X86_AMD_PLATFORM_DEVICE n
IOSF_MBI n
SCHED_OMIT_FRAME_POINTER y
HYPERVISOR_GUEST y
PARAVIRT y
PARAVIRT_DEBUG n
PARAVIRT_SPINLOCKS y
X86_HV_CALLBACK_VECTOR y
XEN n
KVM_GUEST y
ARCH_CPUIDLE_HALTPOLL y
PVH y
PARAVIRT_TIME_ACCOUNTING y
PARAVIRT_CLOCK y
JAILHOUSE_GUEST n
ACRN_GUEST n
MK8 n
MPSC n
MCORE2 n
MATOM n
GENERIC_CPU y
X86_INTERNODE_CACHE_SHIFT 6
X86_L1_CACHE_SHIFT 6
X86_TSC y
X86_CMPXCHG64 y
X86_CMOV y
X86_MINIMUM_CPU_FAMILY 64
X86_DEBUGCTLMSR y
IA32_FEAT_CTL y
X86_VMX_FEATURE_NAMES y
PROCESSOR_SELECT n
CPU_SUP_INTEL y
CPU_SUP_AMD y
CPU_SUP_HYGON y
CPU_SUP_CENTAUR y
CPU_SUP_ZHAOXIN y
HPET_TIMER y
DMI y
GART_IOMMU n
MAXSMP n
NR_CPUS_RANGE_BEGIN 2
NR_CPUS_RANGE_END 512
NR_CPUS_DEFAULT 64
NR_CPUS 128
SCHED_SMT y
SCHED_MC y
SCHED_MC_PRIO y
X86_LOCAL_APIC y
X86_IO_APIC y
X86_REROUTE_FOR_BROKEN_BOOT_IRQS y
X86_MCE n

#
# Performance monitoring
#
PERF_EVENTS_INTEL_UNCORE y
PERF_EVENTS_INTEL_RAPL y
PERF_EVENTS_INTEL_CSTATE y
PERF_EVENTS_AMD_POWER n
PERF_EVENTS_AMD_UNCORE y
# end of Performance monitoring

X86_16BIT y
X86_ESPFIX64 y
X86_VSYSCALL_EMULATION y
X86_IOPL_IOPERM n
MICROCODE n
X86_MSR y
X86_CPUID y
X86_5LEVEL y
X86_DIRECT_GBPAGES y
X86_CPA_STATISTICS n
AMD_MEM_ENCRYPT y
AMD_MEM_ENCRYPT_ACTIVE_BY_DEFAULT n
NUMA y
AMD_NUMA n
X86_64_ACPI_NUMA y
NUMA_EMU n
NODES_SHIFT 10
ARCH_SPARSEMEM_ENABLE y
ARCH_SPARSEMEM_DEFAULT y
ARCH_SELECT_MEMORY_MODEL y
ARCH_MEMORY_PROBE y
ARCH_PROC_KCORE_TEXT y
ILLEGAL_POINTER_VALUE 0xdead000000000000
X86_PMEM_LEGACY n
X86_CHECK_BIOS_CORRUPTION y
X86_BOOTPARAM_MEMORY_CORRUPTION_CHECK y
MTRR y
MTRR_SANITIZER y
MTRR_SANITIZER_ENABLE_DEFAULT 0
MTRR_SANITIZER_SPARE_REG_NR_DEFAULT 1
X86_PAT y
ARCH_USES_PG_UNCACHED y
ARCH_RANDOM y
X86_SMAP y
X86_UMIP n
X86_INTEL_MEMORY_PROTECTION_KEYS n
X86_INTEL_TSX_MODE_OFF y
X86_INTEL_TSX_MODE_ON n
X86_INTEL_TSX_MODE_AUTO n
X86_SGX n
EFI y
EFI_STUB y
EFI_MIXED n
HZ_100 n
HZ_250 y
HZ_300 n
HZ_1000 n
HZ 250
SCHED_HRTICK y
KEXEC n
KEXEC_FILE y
ARCH_HAS_KEXEC_PURGATORY y
KEXEC_SIG n
CRASH_DUMP n
PHYSICAL_START 0x1000000
RELOCATABLE y
RANDOMIZE_BASE y
X86_NEED_RELOCS y
PHYSICAL_ALIGN 0x1000000
DYNAMIC_MEMORY_LAYOUT y
RANDOMIZE_MEMORY y
RANDOMIZE_MEMORY_PHYSICAL_PADDING 0xa
HOTPLUG_CPU y
BOOTPARAM_HOTPLUG_CPU0 n
DEBUG_HOTPLUG_CPU0 n
LEGACY_VSYSCALL_EMULATE y
LEGACY_VSYSCALL_XONLY n
LEGACY_VSYSCALL_NONE n
CMDLINE_BOOL n
MODIFY_LDT_SYSCALL y
HAVE_LIVEPATCH y
# end of Processor type and features

ARCH_HAS_ADD_PAGES y
ARCH_MHP_MEMMAP_ON_MEMORY_ENABLE y
USE_PERCPU_NUMA_NODE_ID y

#
# Power management and ACPI options
#
ARCH_HIBERNATION_HEADER y
SUSPEND n
HIBERNATE_CALLBACKS y
HIBERNATION y
HIBERNATION_SNAPSHOT_DEV n
PM_STD_PARTITION ""
PM_SLEEP y
PM_SLEEP_SMP y
PM_AUTOSLEEP n
PM_WAKELOCKS n
PM y
PM_DEBUG n
PM_CLK y
WQ_POWER_EFFICIENT_DEFAULT n
ENERGY_MODEL n
ARCH_SUPPORTS_ACPI y
ACPI y
ACPI_LEGACY_TABLES_LOOKUP y
ARCH_MIGHT_HAVE_ACPI_PDC y
ACPI_SYSTEM_POWER_STATES_SUPPORT y
ACPI_DEBUGGER n
ACPI_SPCR_TABLE y
ACPI_FPDT n
ACPI_LPIT y
ACPI_SLEEP y
ACPI_REV_OVERRIDE_POSSIBLE y
ACPI_EC_DEBUGFS n
ACPI_AC n
ACPI_BATTERY n
ACPI_BUTTON y
ACPI_VIDEO n
ACPI_FAN n
ACPI_TAD n
ACPI_DOCK n
ACPI_CPU_FREQ_PSS y
ACPI_PROCESSOR_CSTATE y
ACPI_PROCESSOR_IDLE y
ACPI_CPPC_LIB y
ACPI_PROCESSOR y
ACPI_HOTPLUG_CPU y
ACPI_PROCESSOR_AGGREGATOR n
ACPI_THERMAL y
ARCH_HAS_ACPI_TABLE_UPGRADE y
ACPI_TABLE_UPGRADE y
ACPI_DEBUG n
ACPI_PCI_SLOT n
ACPI_CONTAINER y
ACPI_HOTPLUG_MEMORY y
ACPI_HOTPLUG_IOAPIC y
ACPI_SBS n
ACPI_HED n
ACPI_CUSTOM_METHOD n
ACPI_BGRT n
ACPI_REDUCED_HARDWARE_ONLY y
ACPI_NFIT n
ACPI_NUMA y
ACPI_HMAT n
HAVE_ACPI_APEI y
HAVE_ACPI_APEI_NMI y
ACPI_APEI n
ACPI_DPTF n
ACPI_CONFIGFS n
PMIC_OPREGION n
ACPI_VIOT y
X86_PM_TIMER y
ACPI_PRMT n

#
# CPU Frequency scaling
#
CPU_FREQ y
CPU_FREQ_GOV_ATTR_SET y
CPU_FREQ_STAT n
CPU_FREQ_DEFAULT_GOV_PERFORMANCE y
CPU_FREQ_DEFAULT_GOV_POWERSAVE n
CPU_FREQ_DEFAULT_GOV_USERSPACE n
CPU_FREQ_DEFAULT_GOV_SCHEDUTIL n
CPU_FREQ_GOV_PERFORMANCE y
CPU_FREQ_GOV_POWERSAVE n
CPU_FREQ_GOV_USERSPACE n
CPU_FREQ_GOV_ONDEMAND n
CPU_FREQ_GOV_CONSERVATIVE n
CPU_FREQ_GOV_SCHEDUTIL y

#
# CPU frequency scaling drivers
#
X86_INTEL_PSTATE y
X86_PCC_CPUFREQ n
X86_ACPI_CPUFREQ n
X86_SPEEDSTEP_CENTRINO n
X86_P4_CLOCKMOD n

#
# shared options
#
# end of CPU Frequency scaling

#
# CPU Idle
#
CPU_IDLE y
CPU_IDLE_GOV_LADDER y
CPU_IDLE_GOV_MENU y
CPU_IDLE_GOV_TEO n
CPU_IDLE_GOV_HALTPOLL n
HALTPOLL_CPUIDLE n
# end of CPU Idle

INTEL_IDLE y
# end of Power management and ACPI options

#
# Bus options (PCI etc.)
#
PCI_DIRECT y
PCI_MMCONFIG y
MMCONF_FAM10H y
PCI_CNB20LE_QUIRK n
ISA_BUS n
ISA_DMA_API n
AMD_NB y
# end of Bus options (PCI etc.)

#
# Binary Emulations
#
IA32_EMULATION n
X86_X32 n
# end of Binary Emulations

HAVE_KVM y
HAVE_KVM_IRQCHIP y
HAVE_KVM_IRQFD y
HAVE_KVM_IRQ_ROUTING y
HAVE_KVM_EVENTFD y
KVM_MMIO y
KVM_ASYNC_PF y
HAVE_KVM_MSI y
HAVE_KVM_CPU_RELAX_INTERCEPT y
KVM_VFIO y
KVM_GENERIC_DIRTYLOG_READ_PROTECT y
HAVE_KVM_IRQ_BYPASS y
HAVE_KVM_NO_POLL y
KVM_XFER_TO_GUEST_WORK y
HAVE_KVM_PM_NOTIFIER y
VIRTUALIZATION y
KVM y
KVM_WERROR n
KVM_INTEL y
KVM_AMD n
KVM_XEN n
AS_AVX512 y
AS_SHA1_NI y
AS_SHA256_NI y
AS_TPAUSE y

#
# General architecture-dependent options
#
CRASH_CORE y
KEXEC_CORE y
HOTPLUG_SMT y
GENERIC_ENTRY y
JUMP_LABEL y
STATIC_KEYS_SELFTEST n
STATIC_CALL_SELFTEST n
HAVE_EFFICIENT_UNALIGNED_ACCESS y
ARCH_USE_BUILTIN_BSWAP y
USER_RETURN_NOTIFIER y
HAVE_IOREMAP_PROT y
HAVE_KPROBES y
HAVE_KRETPROBES y
HAVE_OPTPROBES y
HAVE_KPROBES_ON_FTRACE y
HAVE_FUNCTION_ERROR_INJECTION y
HAVE_NMI y
TRACE_IRQFLAGS_SUPPORT y
HAVE_ARCH_TRACEHOOK y
HAVE_DMA_CONTIGUOUS y
GENERIC_SMP_IDLE_THREAD y
ARCH_HAS_FORTIFY_SOURCE y
ARCH_HAS_SET_MEMORY y
ARCH_HAS_SET_DIRECT_MAP y
HAVE_ARCH_THREAD_STRUCT_WHITELIST y
ARCH_WANTS_DYNAMIC_TASK_STRUCT y
ARCH_WANTS_NO_INSTR y
HAVE_ASM_MODVERSIONS y
HAVE_REGS_AND_STACK_ACCESS_API y
HAVE_RSEQ y
HAVE_FUNCTION_ARG_ACCESS_API y
HAVE_HW_BREAKPOINT y
HAVE_MIXED_BREAKPOINTS_REGS y
HAVE_USER_RETURN_NOTIFIER y
HAVE_PERF_EVENTS_NMI y
HAVE_HARDLOCKUP_DETECTOR_PERF y
HAVE_PERF_REGS y
HAVE_PERF_USER_STACK_DUMP y
HAVE_ARCH_JUMP_LABEL y
HAVE_ARCH_JUMP_LABEL_RELATIVE y
MMU_GATHER_TABLE_FREE y
MMU_GATHER_RCU_TABLE_FREE y
ARCH_HAVE_NMI_SAFE_CMPXCHG y
HAVE_ALIGNED_STRUCT_PAGE y
HAVE_CMPXCHG_LOCAL y
HAVE_CMPXCHG_DOUBLE y
HAVE_ARCH_SECCOMP y
HAVE_ARCH_SECCOMP_FILTER y
SECCOMP y
SECCOMP_FILTER y
SECCOMP_CACHE_DEBUG n
HAVE_ARCH_STACKLEAK y
HAVE_STACKPROTECTOR y
STACKPROTECTOR y
STACKPROTECTOR_STRONG y
ARCH_SUPPORTS_LTO_CLANG y
ARCH_SUPPORTS_LTO_CLANG_THIN y
LTO_NONE y
HAVE_ARCH_WITHIN_STACK_FRAMES y
HAVE_CONTEXT_TRACKING y
HAVE_CONTEXT_TRACKING_OFFSTACK y
HAVE_VIRT_CPU_ACCOUNTING_GEN y
HAVE_IRQ_TIME_ACCOUNTING y
HAVE_MOVE_PUD y
HAVE_MOVE_PMD y
HAVE_ARCH_TRANSPARENT_HUGEPAGE y
HAVE_ARCH_TRANSPARENT_HUGEPAGE_PUD y
HAVE_ARCH_HUGE_VMAP y
ARCH_WANT_HUGE_PMD_SHARE y
HAVE_ARCH_SOFT_DIRTY y
HAVE_MOD_ARCH_SPECIFIC y
MODULES_USE_ELF_RELA y
HAVE_IRQ_EXIT_ON_IRQ_STACK y
HAVE_SOFTIRQ_ON_OWN_STACK y
ARCH_HAS_ELF_RANDOMIZE y
HAVE_ARCH_MMAP_RND_BITS y
HAVE_EXIT_THREAD y
ARCH_MMAP_RND_BITS 28
HAVE_STACK_VALIDATION y
HAVE_RELIABLE_STACKTRACE y
COMPAT_32BIT_TIME n
HAVE_ARCH_VMAP_STACK y
VMAP_STACK y
HAVE_ARCH_RANDOMIZE_KSTACK_OFFSET y
RANDOMIZE_KSTACK_OFFSET_DEFAULT n
ARCH_HAS_STRICT_KERNEL_RWX y
STRICT_KERNEL_RWX y
ARCH_HAS_STRICT_MODULE_RWX y
HAVE_ARCH_PREL32_RELOCATIONS y
ARCH_USE_MEMREMAP_PROT y
LOCK_EVENT_COUNTS n
ARCH_HAS_MEM_ENCRYPT y
ARCH_HAS_CC_PLATFORM y
HAVE_STATIC_CALL y
HAVE_STATIC_CALL_INLINE y
HAVE_PREEMPT_DYNAMIC y
ARCH_WANT_LD_ORPHAN_WARN y
ARCH_SUPPORTS_DEBUG_PAGEALLOC y
ARCH_HAS_ELFCORE_COMPAT y
ARCH_HAS_PARANOID_L1D_FLUSH y

#
# GCOV-based kernel profiling
#
GCOV_KERNEL n
ARCH_HAS_GCOV_PROFILE_ALL y
# end of GCOV-based kernel profiling

HAVE_GCC_PLUGINS y
# end of General architecture-dependent options

RT_MUTEXES y
BASE_SMALL 0
MODULES n
MODULES_TREE_LOOKUP y
BLOCK y
BLK_CGROUP_RWSTAT y
BLK_DEV_BSG_COMMON y
BLK_DEV_BSGLIB y
BLK_DEV_INTEGRITY y
BLK_DEV_INTEGRITY_T10 y
BLK_DEV_ZONED n
BLK_DEV_THROTTLING y
BLK_DEV_THROTTLING_LOW n
BLK_WBT y
BLK_WBT_MQ y
BLK_CGROUP_IOLATENCY n
BLK_CGROUP_IOCOST n
BLK_CGROUP_IOPRIO n
BLK_DEBUG_FS y
BLK_SED_OPAL n
BLK_INLINE_ENCRYPTION n

#
# Partition Types
#
PARTITION_ADVANCED y
ACORN_PARTITION n
AIX_PARTITION n
OSF_PARTITION n
AMIGA_PARTITION n
ATARI_PARTITION n
MAC_PARTITION n
MSDOS_PARTITION n
LDM_PARTITION n
SGI_PARTITION n
ULTRIX_PARTITION n
SUN_PARTITION n
KARMA_PARTITION n
EFI_PARTITION y
SYSV68_PARTITION n
CMDLINE_PARTITION n
# end of Partition Types

BLK_MQ_PCI y
BLK_MQ_VIRTIO y
BLK_PM y
BLOCK_HOLDER_DEPRECATED y

#
# IO Schedulers
#
MQ_IOSCHED_DEADLINE n
MQ_IOSCHED_KYBER n
IOSCHED_BFQ n
# end of IO Schedulers

PREEMPT_NOTIFIERS y
INLINE_SPIN_UNLOCK_IRQ y
INLINE_READ_UNLOCK y
INLINE_READ_UNLOCK_IRQ y
INLINE_WRITE_UNLOCK y
INLINE_WRITE_UNLOCK_IRQ y
ARCH_SUPPORTS_ATOMIC_RMW y
MUTEX_SPIN_ON_OWNER y
RWSEM_SPIN_ON_OWNER y
LOCK_SPIN_ON_OWNER y
ARCH_USE_QUEUED_SPINLOCKS y
QUEUED_SPINLOCKS y
ARCH_USE_QUEUED_RWLOCKS y
QUEUED_RWLOCKS y
ARCH_HAS_NON_OVERLAPPING_ADDRESS_SPACE y
ARCH_HAS_SYNC_CORE_BEFORE_USERMODE y
ARCH_HAS_SYSCALL_WRAPPER y
FREEZER y

#
# Executable file formats
#
BINFMT_ELF y
ELFCORE y
CORE_DUMP_DEFAULT_ELF_HEADERS y
BINFMT_SCRIPT y
BINFMT_MISC y
COREDUMP y
# end of Executable file formats

#
# Memory Management options
#
SELECT_MEMORY_MODEL y
SPARSEMEM_MANUAL y
SPARSEMEM y
SPARSEMEM_EXTREME y
SPARSEMEM_VMEMMAP_ENABLE y
SPARSEMEM_VMEMMAP y
HAVE_FAST_GUP y
NUMA_KEEP_MEMINFO y
MEMORY_ISOLATION y
HAVE_BOOTMEM_INFO_NODE y
ARCH_ENABLE_MEMORY_HOTPLUG y
MEMORY_HOTPLUG y
MEMORY_HOTPLUG_SPARSE y
MEMORY_HOTPLUG_DEFAULT_ONLINE y
ARCH_ENABLE_MEMORY_HOTREMOVE y
MEMORY_HOTREMOVE y
MHP_MEMMAP_ON_MEMORY y
SPLIT_PTLOCK_CPUS 4
ARCH_ENABLE_SPLIT_PMD_PTLOCK y
MEMORY_BALLOON y
BALLOON_COMPACTION y
COMPACTION y
PAGE_REPORTING y
MIGRATION y
ARCH_ENABLE_HUGEPAGE_MIGRATION y
ARCH_ENABLE_THP_MIGRATION y
CONTIG_ALLOC y
PHYS_ADDR_T_64BIT y
VIRT_TO_BUS y
MMU_NOTIFIER y
KSM y
DEFAULT_MMAP_MIN_ADDR 4096
TRANSPARENT_HUGEPAGE y
TRANSPARENT_HUGEPAGE_ALWAYS n
TRANSPARENT_HUGEPAGE_MADVISE y
ARCH_WANTS_THP_SWAP y
THP_SWAP y
CLEANCACHE y
FRONTSWAP y
CMA n
ZSWAP y
ZSWAP_COMPRESSOR_DEFAULT_DEFLATE n
ZSWAP_COMPRESSOR_DEFAULT_LZO y
ZSWAP_COMPRESSOR_DEFAULT_842 n
ZSWAP_COMPRESSOR_DEFAULT_LZ4 n
ZSWAP_COMPRESSOR_DEFAULT_LZ4HC n
ZSWAP_COMPRESSOR_DEFAULT_ZSTD n
ZSWAP_COMPRESSOR_DEFAULT lzo
ZSWAP_ZPOOL_DEFAULT_ZBUD y
ZSWAP_ZPOOL_DEFAULT_Z3FOLD n
ZSWAP_ZPOOL_DEFAULT_ZSMALLOC n
ZSWAP_ZPOOL_DEFAULT zbud
ZSWAP_DEFAULT_ON n
ZPOOL y
ZBUD y
Z3FOLD n
ZSMALLOC y
ZSMALLOC_STAT y
GENERIC_EARLY_IOREMAP y
DEFERRED_STRUCT_PAGE_INIT n
IDLE_PAGE_TRACKING n
ARCH_HAS_CACHE_LINE_SIZE y
ARCH_HAS_PTE_DEVMAP y
ARCH_HAS_ZONE_DMA_SET y
ZONE_DMA y
ZONE_DMA32 y
ZONE_DEVICE y
DEV_PAGEMAP_OPS y
DEVICE_PRIVATE n
PERCPU_STATS y
GUP_TEST n
READ_ONLY_THP_FOR_FS n
ARCH_HAS_PTE_SPECIAL y
SECRETMEM y

#
# Data Access Monitoring
#
DAMON n
# end of Data Access Monitoring
# end of Memory Management options

NET y
SKB_EXTENSIONS y

#
# Networking options
#
PACKET y
PACKET_DIAG y
UNIX y
UNIX_SCM y
AF_UNIX_OOB y
UNIX_DIAG y
TLS y
TLS_DEVICE n
TLS_TOE n
XFRM y
XFRM_ALGO y
XFRM_USER y
XFRM_SUB_POLICY y
XFRM_MIGRATE y
XFRM_STATISTICS y
NET_KEY y
NET_KEY_MIGRATE y
XDP_SOCKETS n
XDP_SOCKETS_DIAG n
INET y
IP_MULTICAST n
IP_ADVANCED_ROUTER n
IP_PNP y
IP_PNP_DHCP y
IP_PNP_BOOTP y
IP_PNP_RARP y
NET_IPIP n
NET_IPGRE_DEMUX n
SYN_COOKIES y
NET_IPVTI n
NET_FOU n
INET_AH n
INET_ESP n
INET_IPCOMP n
INET_DIAG y
INET_TCP_DIAG y
INET_UDP_DIAG y
INET_RAW_DIAG y
INET_DIAG_DESTROY n
TCP_CONG_ADVANCED n
TCP_CONG_CUBIC y
DEFAULT_TCP_CONG "cubic"
TCP_MD5SIG n
IPV6 n
MPTCP n
NETWORK_SECMARK n
NET_PTP_CLASSIFY y
NETWORK_PHY_TIMESTAMPING n
NETFILTER n
BPFILTER n
IP_DCCP n
IP_SCTP n
RDS n
TIPC n
ATM n
L2TP n
BRIDGE n
NET_DSA n
VLAN_8021Q n
DECNET n
LLC2 n
ATALK n
X25 n
LAPB n
PHONET n
IEEE802154 n
NET_SCHED n
DCB n
DNS_RESOLVER n
BATMAN_ADV n
OPENVSWITCH n
VSOCKETS y
VSOCKETS_DIAG y
VSOCKETS_LOOPBACK n
VIRTIO_VSOCKETS y
VIRTIO_VSOCKETS_COMMON y
HYPERV_VSOCKETS n
NETLINK_DIAG n
MPLS n
NET_NSH n
HSR n
NET_SWITCHDEV n
NET_L3_MASTER_DEV n
QRTR n
NET_NCSI n
PCPU_DEV_REFCNT y
RPS y
RFS_ACCEL y
SOCK_RX_QUEUE_MAPPING y
XPS y
CGROUP_NET_PRIO y
CGROUP_NET_CLASSID y
NET_RX_BUSY_POLL y
BQL y
BPF_STREAM_PARSER n
NET_FLOW_LIMIT y

#
# Network testing
#
NET_PKTGEN n
# end of Network testing
# end of Networking options

HAMRADIO n
CAN n
BT n
AF_RXRPC n
AF_KCM n
STREAM_PARSER y
MCTP n
WIRELESS n
RFKILL n
NET_9P n
CAIF n
CEPH_LIB n
NFC n
PSAMPLE n
NET_IFE n
LWTUNNEL n
GRO_CELLS y
NET_SOCK_MSG y
FAILOVER y
ETHTOOL_NETLINK n

#
# Device Drivers
#
HAVE_EISA y
EISA n
HAVE_PCI y
PCI y
PCI_DOMAINS y
PCIEPORTBUS y
HOTPLUG_PCI_PCIE n
PCIEAER y
PCIEAER_INJECT n
PCIE_ECRC n
PCIEASPM y
PCIEASPM_DEFAULT y
PCIEASPM_POWERSAVE n
PCIEASPM_POWER_SUPERSAVE n
PCIEASPM_PERFORMANCE n
PCIE_PME y
PCIE_DPC n
PCIE_PTM n
PCI_MSI y
PCI_MSI_IRQ_DOMAIN y
PCI_QUIRKS y
PCI_DEBUG y
PCI_STUB y
PCI_LOCKLESS_CONFIG y
PCI_IOV n
PCI_PRI n
PCI_PASID n
PCI_P2PDMA n
PCI_LABEL y
PCI_HYPERV n
PCIE_BUS_TUNE_OFF n
PCIE_BUS_DEFAULT y
PCIE_BUS_SAFE n
PCIE_BUS_PERFORMANCE n
PCIE_BUS_PEER2PEER n
HOTPLUG_PCI y
HOTPLUG_PCI_ACPI y
HOTPLUG_PCI_ACPI_IBM n
HOTPLUG_PCI_CPCI n
HOTPLUG_PCI_SHPC n

#
# PCI controller drivers
#
VMD n
PCI_HYPERV_INTERFACE n

#
# DesignWare PCI Core Support
#
PCIE_DW_PLAT_HOST n
PCI_MESON n
# end of DesignWare PCI Core Support

#
# Mobiveil PCIe Core Support
#
# end of Mobiveil PCIe Core Support

#
# Cadence PCIe controllers support
#
# end of Cadence PCIe controllers support
# end of PCI controller drivers

#
# PCI Endpoint
#
PCI_ENDPOINT n
# end of PCI Endpoint

#
# PCI switch controller drivers
#
PCI_SW_SWITCHTEC n
# end of PCI switch controller drivers

CXL_BUS n
PCCARD n
RAPIDIO n

#
# Generic Driver Options
#
UEVENT_HELPER y
UEVENT_HELPER_PATH "/sbin/hotplug"
DEVTMPFS y
DEVTMPFS_MOUNT y
STANDALONE y
PREVENT_FIRMWARE_BUILD y

#
# Firmware loader
#
FW_LOADER y
FW_LOADER_PAGED_BUF y
EXTRA_FIRMWARE ""
FW_LOADER_USER_HELPER y
FW_LOADER_USER_HELPER_FALLBACK n
FW_LOADER_COMPRESS n
FW_CACHE n
# end of Firmware loader

ALLOW_DEV_COREDUMP y
DEBUG_DRIVER n
DEBUG_DEVRES n
DEBUG_TEST_DRIVER_REMOVE n
GENERIC_CPU_AUTOPROBE y
GENERIC_CPU_VULNERABILITIES y
# end of Generic Driver Options

#
# Bus devices
#
MHI_BUS n
# end of Bus devices

CONNECTOR y
PROC_EVENTS y

#
# Firmware Drivers
#

#
# ARM System Control and Management Interface Protocol
#
# end of ARM System Control and Management Interface Protocol

EDD n
FIRMWARE_MEMMAP y
DMIID y
DMI_SYSFS y
DMI_SCAN_MACHINE_NON_EFI_FALLBACK y
FW_CFG_SYSFS n
SYSFB y
SYSFB_SIMPLEFB n
GOOGLE_FIRMWARE n

#
# EFI (Extensible Firmware Interface) Support
#
EFI_VARS n
EFI_ESRT y
EFI_RUNTIME_MAP y
EFI_FAKE_MEMMAP n
EFI_RUNTIME_WRAPPERS y
EFI_GENERIC_STUB_INITRD_CMDLINE_LOADER y
EFI_BOOTLOADER_CONTROL n
EFI_CAPSULE_LOADER n
EFI_TEST n
APPLE_PROPERTIES n
RESET_ATTACK_MITIGATION n
EFI_RCI2_TABLE n
EFI_DISABLE_PCI_DMA n
# end of EFI (Extensible Firmware Interface) Support

EFI_EARLYCON y
EFI_CUSTOM_SSDT_OVERLAYS n

#
# Tegra firmware driver
#
# end of Tegra firmware driver
# end of Firmware Drivers

GNSS n
MTD n
OF n
ARCH_MIGHT_HAVE_PC_PARPORT y
PARPORT n
PNP y
PNP_DEBUG_MESSAGES n

#
# Protocols
#
PNPACPI y
BLK_DEV y
BLK_DEV_NULL_BLK y
BLK_DEV_PCIESSD_MTIP32XX n
ZRAM y
ZRAM_DEF_COMP_LZORLE y
ZRAM_DEF_COMP_LZO n
ZRAM_DEF_COMP lzo-rle
ZRAM_WRITEBACK n
ZRAM_MEMORY_TRACKING n
BLK_DEV_LOOP y
BLK_DEV_LOOP_MIN_COUNT 8
BLK_DEV_CRYPTOLOOP y
BLK_DEV_DRBD n
BLK_DEV_NBD n
BLK_DEV_SX8 n
BLK_DEV_RAM y
BLK_DEV_RAM_COUNT 16
BLK_DEV_RAM_SIZE 16384
CDROM_PKTCDVD n
ATA_OVER_ETH n
VIRTIO_BLK y
BLK_DEV_RBD n
BLK_DEV_RSXX n

#
# NVME Support
#
NVME_CORE y
BLK_DEV_NVME y
NVME_MULTIPATH y
NVME_FC n
NVME_TCP n
NVME_TARGET n
# end of NVME Support

#
# Misc devices
#
DUMMY_IRQ n
IBM_ASM n
PHANTOM n
TIFM_CORE n
ENCLOSURE_SERVICES n
HP_ILO n
SRAM n
DW_XDATA_PCIE n
PCI_ENDPOINT_TEST n
XILINX_SDFEC n
C2PORT n

#
# EEPROM support
#
EEPROM_93CX6 n
# end of EEPROM support

CB710_CORE n

#
# Texas Instruments shared transport line discipline
#
TI_ST n
# end of Texas Instruments shared transport line discipline

#
# Altera FPGA firmware download module (requires I2C)
#
INTEL_MEI n
INTEL_MEI_ME n
INTEL_MEI_TXE n
VMWARE_VMCI n
GENWQE n
ECHO n
BCM_VK n
MISC_ALCOR_PCI n
MISC_RTSX_PCI n
HABANA_AI n
UACCE n
PVPANIC n
# end of Misc devices

#
# SCSI device support
#
SCSI_MOD y
RAID_ATTRS n
SCSI n
# end of SCSI device support

ATA n
MD y
BLK_DEV_MD n
BCACHE n
BLK_DEV_DM_BUILTIN y
BLK_DEV_DM y
DM_DEBUG n
DM_UNSTRIPED n
DM_CRYPT n
DM_SNAPSHOT n
DM_THIN_PROVISIONING n
DM_CACHE n
DM_WRITECACHE n
DM_EBS n
DM_ERA n
DM_CLONE n
DM_MIRROR n
DM_RAID n
DM_ZERO n
DM_MULTIPATH y
DM_MULTIPATH_QL n
DM_MULTIPATH_ST n
DM_MULTIPATH_HST n
DM_MULTIPATH_IOA n
DM_DELAY n
DM_DUST n
DM_INIT n
DM_UEVENT n
DM_FLAKEY n
DM_VERITY n
DM_SWITCH n
DM_LOG_WRITES n
DM_INTEGRITY n
TARGET_CORE n
FUSION n

#
# IEEE 1394 (FireWire) support
#
FIREWIRE n
FIREWIRE_NOSY n
# end of IEEE 1394 (FireWire) support

MACINTOSH_DRIVERS n
NETDEVICES y
NET_CORE y
BONDING n
DUMMY n
WIREGUARD n
EQUALIZER n
NET_TEAM n
MACVLAN n
IPVLAN n
VXLAN n
GENEVE n
BAREUDP n
GTP n
MACSEC n
NETCONSOLE n
TUN y
TUN_VNET_CROSS_LE n
VETH y
VIRTIO_NET y
NLMON n
ARCNET n
ETHERNET n
FDDI n
HIPPI n
NET_SB1000 n
PHYLIB n
MDIO_DEVICE n

#
# PCS device drivers
#
# end of PCS device drivers

PPP n
SLIP n

#
# Host-side USB support is needed for USB Network Adapter support
#
WLAN n
WAN n

#
# Wireless WAN
#
WWAN n
# end of Wireless WAN

VMXNET3 n
FUJITSU_ES n
HYPERV_NET n
NETDEVSIM n
NET_FAILOVER y
ISDN n

#
# Input device support
#
INPUT y
INPUT_FF_MEMLESS y
INPUT_SPARSEKMAP y
INPUT_MATRIXKMAP n

#
# Userland interfaces
#
INPUT_MOUSEDEV y
INPUT_MOUSEDEV_PSAUX y
INPUT_MOUSEDEV_SCREEN_X 1024
INPUT_MOUSEDEV_SCREEN_Y 768
INPUT_JOYDEV n
INPUT_EVDEV y
INPUT_EVBUG n

#
# Input Device Drivers
#
INPUT_KEYBOARD y
KEYBOARD_ATKBD n
KEYBOARD_LKKBD n
KEYBOARD_GPIO n
KEYBOARD_GPIO_POLLED n
KEYBOARD_MATRIX n
KEYBOARD_NEWTON n
KEYBOARD_OPENCORES n
KEYBOARD_SAMSUNG n
KEYBOARD_STOWAWAY n
KEYBOARD_SUNKBD n
KEYBOARD_XTKBD n
INPUT_MOUSE n
INPUT_JOYSTICK n
INPUT_TABLET n
INPUT_TOUCHSCREEN n
INPUT_MISC y
INPUT_AD714X n
INPUT_E3X0_BUTTON n
INPUT_PCSPKR n
INPUT_GPIO_BEEPER n
INPUT_GPIO_DECODER n
INPUT_GPIO_VIBRA n
INPUT_ATLAS_BTNS n
INPUT_UINPUT y
INPUT_GPIO_ROTARY_ENCODER n
INPUT_ADXL34X n
INPUT_CMA3000 n
RMI4_CORE n

#
# Hardware I/O ports
#
SERIO n
ARCH_MIGHT_HAVE_PC_SERIO y
GAMEPORT n
# end of Hardware I/O ports
# end of Input device support

#
# Character devices
#
TTY y
VT y
CONSOLE_TRANSLATIONS y
VT_CONSOLE y
VT_CONSOLE_SLEEP y
HW_CONSOLE y
VT_HW_CONSOLE_BINDING y
UNIX98_PTYS y
LEGACY_PTYS n
LDISC_AUTOLOAD n

#
# Serial drivers
#
SERIAL_EARLYCON y
SERIAL_8250 y
SERIAL_8250_DEPRECATED_OPTIONS n
SERIAL_8250_PNP y
SERIAL_8250_16550A_VARIANTS n
SERIAL_8250_FINTEK n
SERIAL_8250_CONSOLE y
SERIAL_8250_DMA y
SERIAL_8250_PCI y
SERIAL_8250_EXAR y
SERIAL_8250_NR_UARTS 1
SERIAL_8250_RUNTIME_UARTS 1
SERIAL_8250_EXTENDED n
SERIAL_8250_DWLIB y
SERIAL_8250_DW n
SERIAL_8250_RT288X n
SERIAL_8250_LPSS y
SERIAL_8250_MID y

#
# Non-8250 serial port support
#
SERIAL_UARTLITE n
SERIAL_CORE y
SERIAL_CORE_CONSOLE y
SERIAL_JSM n
SERIAL_LANTIQ n
SERIAL_SCCNXP n
SERIAL_BCM63XX n
SERIAL_ALTERA_JTAGUART n
SERIAL_ALTERA_UART n
SERIAL_ARC y
SERIAL_ARC_CONSOLE n
SERIAL_ARC_NR_PORTS 1
SERIAL_RP2 n
SERIAL_FSL_LPUART n
SERIAL_FSL_LINFLEXUART n
SERIAL_SPRD n
# end of Serial drivers

SERIAL_MCTRL_GPIO y
SERIAL_NONSTANDARD n
N_GSM n
NOZOMI n
NULL_TTY n
HVC_DRIVER y
SERIAL_DEV_BUS y
SERIAL_DEV_CTRL_TTYPORT y
TTY_PRINTK n
VIRTIO_CONSOLE y
IPMI_HANDLER n
HW_RANDOM y
HW_RANDOM_TIMERIOMEM n
HW_RANDOM_INTEL y
HW_RANDOM_AMD y
HW_RANDOM_BA431 n
HW_RANDOM_VIA y
HW_RANDOM_VIRTIO y
HW_RANDOM_XIPHERA n
APPLICOM n
MWAVE n
DEVMEM y
NVRAM y
DEVPORT y
HPET n
HANGCHECK_TIMER y
TCG_TPM n
TELCLOCK n
XILLYBUS n
RANDOM_TRUST_CPU n
RANDOM_TRUST_BOOTLOADER n
# end of Character devices

#
# I2C support
#
I2C n
# end of I2C support

I3C n
SPI n
SPMI n
HSI n
PPS y
PPS_DEBUG n

#
# PPS clients support
#
PPS_CLIENT_KTIMER n
PPS_CLIENT_LDISC n
PPS_CLIENT_GPIO n

#
# PPS generators support
#

#
# PTP clock support
#
PTP_1588_CLOCK y
PTP_1588_CLOCK_OPTIONAL y

#
# Enable PHYLIB and NETWORK_PHY_TIMESTAMPING to see the additional clocks.
#
PTP_1588_CLOCK_KVM y
PTP_1588_CLOCK_VMW n
# end of PTP clock support

PINCTRL n
GPIOLIB y
GPIOLIB_FASTPATH_LIMIT 512
GPIO_ACPI y
GPIOLIB_IRQCHIP y
DEBUG_GPIO n
GPIO_SYSFS y
GPIO_CDEV y
GPIO_CDEV_V1 y

#
# Memory mapped GPIO drivers
#
GPIO_AMDPT n
GPIO_DWAPB n
GPIO_EXAR n
GPIO_GENERIC_PLATFORM n
GPIO_MB86S7X n
GPIO_VX855 n
GPIO_AMD_FCH n
# end of Memory mapped GPIO drivers

#
# Port-mapped I/O GPIO drivers
#
GPIO_F7188X n
GPIO_IT87 n
GPIO_SCH311X n
GPIO_WINBOND n
GPIO_WS16C48 n
# end of Port-mapped I/O GPIO drivers

#
# MFD GPIO expanders
#
# end of MFD GPIO expanders

#
# PCI GPIO expanders
#
GPIO_AMD8111 n
GPIO_BT8XX n
GPIO_ML_IOH n
GPIO_PCI_IDIO_16 y
GPIO_PCIE_IDIO_24 n
GPIO_RDC321X n
# end of PCI GPIO expanders

#
# Virtual GPIO drivers
#
GPIO_AGGREGATOR n
GPIO_MOCKUP n
GPIO_VIRTIO n
# end of Virtual GPIO drivers

W1 n
POWER_RESET n
POWER_SUPPLY n
HWMON n
THERMAL y
THERMAL_NETLINK n
THERMAL_STATISTICS n
THERMAL_EMERGENCY_POWEROFF_DELAY_MS 0
THERMAL_WRITABLE_TRIPS y
THERMAL_DEFAULT_GOV_STEP_WISE y
THERMAL_DEFAULT_GOV_FAIR_SHARE n
THERMAL_DEFAULT_GOV_USER_SPACE n
THERMAL_GOV_FAIR_SHARE y
THERMAL_GOV_STEP_WISE y
THERMAL_GOV_BANG_BANG n
THERMAL_GOV_USER_SPACE y
THERMAL_EMULATION n

#
# Intel thermal drivers
#
INTEL_POWERCLAMP n
X86_THERMAL_VECTOR y
X86_PKG_TEMP_THERMAL n
INTEL_SOC_DTS_THERMAL n

#
# ACPI INT340X thermal drivers
#
INT340X_THERMAL n
# end of ACPI INT340X thermal drivers

INTEL_PCH_THERMAL n
INTEL_TCC_COOLING n
INTEL_MENLOW n
# end of Intel thermal drivers

WATCHDOG y
WATCHDOG_CORE y
WATCHDOG_NOWAYOUT n
WATCHDOG_HANDLE_BOOT_ENABLED y
WATCHDOG_OPEN_TIMEOUT 0
WATCHDOG_SYSFS n
WATCHDOG_HRTIMER_PRETIMEOUT n

#
# Watchdog Pretimeout Governors
#
WATCHDOG_PRETIMEOUT_GOV n

#
# Watchdog Device Drivers
#
SOFT_WATCHDOG n
WDAT_WDT n
XILINX_WATCHDOG n
CADENCE_WATCHDOG n
DW_WATCHDOG n
MAX63XX_WATCHDOG n
ACQUIRE_WDT n
ADVANTECH_WDT n
ALIM1535_WDT n
ALIM7101_WDT n
EBC_C384_WDT n
F71808E_WDT n
SP5100_TCO n
SBC_FITPC2_WATCHDOG n
EUROTECH_WDT n
IB700_WDT n
IBMASR n
WAFER_WDT n
I6300ESB_WDT n
IE6XX_WDT n
ITCO_WDT n
IT8712F_WDT n
IT87_WDT n
HP_WATCHDOG n
SC1200_WDT n
PC87413_WDT n
NV_TCO n
60XX_WDT n
CPU5_WDT n
SMSC_SCH311X_WDT n
SMSC37B787_WDT n
TQMX86_WDT n
VIA_WDT n
W83627HF_WDT n
W83877F_WDT n
W83977F_WDT n
MACHZ_WDT n
SBC_EPX_C3_WATCHDOG n
NI903X_WDT n
NIC7018_WDT n
MEN_A21_WDT n

#
# PCI-based Watchdog Cards
#
PCIPCWATCHDOG n
WDTPCI n
SSB_POSSIBLE y
SSB n
BCMA_POSSIBLE y
BCMA n

#
# Multifunction device drivers
#
MFD_MADERA n
HTC_PASIC3 n
MFD_INTEL_QUARK_I2C_GPIO n
LPC_ICH n
LPC_SCH n
MFD_INTEL_LPSS_ACPI n
MFD_INTEL_LPSS_PCI n
MFD_INTEL_PMT n
MFD_JANZ_CMODIO n
MFD_KEMPLD n
MFD_MT6397 n
MFD_RDC321X n
MFD_SM501 n
MFD_SYSCON n
MFD_TI_AM335X_TSCADC n
MFD_TQMX86 n
MFD_VX855 n
RAVE_SP_CORE n
# end of Multifunction device drivers

REGULATOR n
RC_CORE n
MEDIA_CEC_SUPPORT n
MEDIA_SUPPORT n

#
# Graphics support
#
AGP n
VGA_ARB y
VGA_ARB_MAX_GPUS 16
VGA_SWITCHEROO n
DRM n

#
# ARM devices
#
# end of ARM devices

#
# Frame buffer Devices
#
FB_CMDLINE y
FB_NOTIFY y
FB y
FIRMWARE_EDID n
FB_FOREIGN_ENDIAN n
FB_MODE_HELPERS n
FB_TILEBLITTING n

#
# Frame buffer hardware drivers
#
FB_CIRRUS n
FB_PM2 n
FB_CYBER2000 n
FB_ARC n
FB_ASILIANT n
FB_IMSTT n
FB_VGA16 n
FB_UVESA n
FB_VESA n
FB_EFI n
FB_N411 n
FB_HGA n
FB_OPENCORES n
FB_S1D13XXX n
FB_NVIDIA n
FB_RIVA n
FB_I740 n
FB_LE80578 n
FB_MATROX n
FB_RADEON n
FB_ATY128 n
FB_ATY n
FB_S3 n
FB_SAVAGE n
FB_SIS n
FB_NEOMAGIC n
FB_KYRO n
FB_3DFX n
FB_VOODOO1 n
FB_VT8623 n
FB_TRIDENT n
FB_ARK n
FB_PM3 n
FB_CARMINE n
FB_IBM_GXT4500 n
FB_VIRTUAL n
FB_METRONOME n
FB_MB862XX n
FB_HYPERV n
FB_SIMPLE n
FB_SM712 n
# end of Frame buffer Devices

#
# Backlight & LCD device support
#
LCD_CLASS_DEVICE y
LCD_PLATFORM n
BACKLIGHT_CLASS_DEVICE y
BACKLIGHT_KTD253 n
BACKLIGHT_APPLE n
BACKLIGHT_QCOM_WLED n
BACKLIGHT_SAHARA n
BACKLIGHT_GPIO n
# end of Backlight & LCD device support

#
# Console display driver support
#
VGA_CONSOLE y
DUMMY_CONSOLE y
DUMMY_CONSOLE_COLUMNS 80
DUMMY_CONSOLE_ROWS 25
FRAMEBUFFER_CONSOLE y
FRAMEBUFFER_CONSOLE_DETECT_PRIMARY y
FRAMEBUFFER_CONSOLE_ROTATION n
FRAMEBUFFER_CONSOLE_DEFERRED_TAKEOVER n
# end of Console display driver support

LOGO n
# end of Graphics support

SOUND n

#
# HID support
#
HID y
HID_BATTERY_STRENGTH n
HIDRAW y
UHID y
HID_GENERIC y

#
# Special HID drivers
#
HID_A4TECH n
HID_ACRUX n
HID_APPLE n
HID_AUREAL n
HID_BELKIN n
HID_CHERRY n
HID_COUGAR n
HID_MACALLY n
HID_CMEDIA n
HID_CYPRESS n
HID_DRAGONRISE n
HID_EMS_FF n
HID_ELECOM n
HID_EZKEY n
HID_GEMBIRD n
HID_GFRM n
HID_GLORIOUS n
HID_VIVALDI n
HID_KEYTOUCH n
HID_KYE n
HID_WALTOP n
HID_VIEWSONIC n
HID_GYRATION n
HID_ICADE n
HID_ITE n
HID_JABRA n
HID_TWINHAN n
HID_KENSINGTON n
HID_LCPOWER n
HID_LENOVO n
HID_MAGICMOUSE n
HID_MALTRON n
HID_MAYFLASH n
HID_REDRAGON y
HID_MICROSOFT n
HID_MONTEREY n
HID_MULTITOUCH n
HID_NTI n
HID_ORTEK n
HID_PANTHERLORD n
HID_PETALYNX n
HID_PICOLCD n
HID_PLANTRONICS n
HID_PLAYSTATION n
HID_PRIMAX n
HID_SAITEK n
HID_SEMITEK n
HID_SPEEDLINK n
HID_STEAM n
HID_STEELSERIES n
HID_SUNPLUS n
HID_RMI n
HID_GREENASIA n
HID_HYPERV_MOUSE n
HID_SMARTJOYPLUS n
HID_TIVO n
HID_TOPSEED n
HID_UDRAW_PS3 n
HID_XINMO n
HID_ZEROPLUS y
HID_ZYDACRON n
HID_SENSOR_HUB n
HID_ALPS n
# end of Special HID drivers

#
# Intel ISH HID support
#
INTEL_ISH_HID n
# end of Intel ISH HID support

#
# AMD SFH HID Support
#
AMD_SFH_HID n
# end of AMD SFH HID Support
# end of HID support

USB_OHCI_LITTLE_ENDIAN y
USB_SUPPORT n
MMC n
MEMSTICK n
NEW_LEDS n
ACCESSIBILITY n
INFINIBAND n
EDAC_ATOMIC_SCRUB y
EDAC_SUPPORT y
EDAC n
RTC_LIB y
RTC_MC146818_LIB y
RTC_CLASS n
DMADEVICES y
DMADEVICES_DEBUG n

#
# DMA Devices
#
DMA_ENGINE y
DMA_VIRTUAL_CHANNELS y
DMA_ACPI y
ALTERA_MSGDMA n
INTEL_IDMA64 n
INTEL_IDXD_COMPAT n
INTEL_IOATDMA n
PLX_DMA n
AMD_PTDMA n
QCOM_HIDMA_MGMT n
QCOM_HIDMA n
DW_DMAC_CORE y
DW_DMAC n
DW_DMAC_PCI n
DW_EDMA n
DW_EDMA_PCIE n
HSU_DMA y
SF_PDMA n
INTEL_LDMA n

#
# DMA Clients
#
ASYNC_TX_DMA n
DMATEST n

#
# DMABUF options
#
SYNC_FILE n
DMABUF_HEAPS n
# end of DMABUF options

AUXDISPLAY n
UIO y
UIO_CIF n
UIO_PDRV_GENIRQ y
UIO_DMEM_GENIRQ y
UIO_AEC n
UIO_SERCOS3 n
UIO_PCI_GENERIC n
UIO_NETX n
UIO_PRUSS n
UIO_MF624 n
UIO_HV_GENERIC n
VFIO y
VFIO_IOMMU_TYPE1 y
VFIO_VIRQFD y
VFIO_NOIOMMU n
VFIO_PCI_CORE y
VFIO_PCI_MMAP y
VFIO_PCI_INTX y
VFIO_PCI y
VFIO_PCI_VGA n
VFIO_PCI_IGD n
VFIO_MDEV n
IRQ_BYPASS_MANAGER y
VIRT_DRIVERS n
VIRTIO y
ARCH_HAS_RESTRICTED_VIRTIO_MEMORY_ACCESS y
VIRTIO_PCI_LIB y
VIRTIO_MENU y
VIRTIO_PCI y
VIRTIO_PCI_LEGACY y
VIRTIO_PMEM y
VIRTIO_BALLOON y
VIRTIO_MEM y
VIRTIO_INPUT y
VIRTIO_MMIO y
VIRTIO_MMIO_CMDLINE_DEVICES y
VDPA n
VHOST_MENU n

#
# Microsoft Hyper-V guest support
#
HYPERV y
HYPERV_TIMER y
HYPERV_UTILS n
HYPERV_BALLOON n
# end of Microsoft Hyper-V guest support

GREYBUS n
COMEDI n
STAGING n
X86_PLATFORM_DEVICES n
PMC_ATOM y
CHROME_PLATFORMS n
MELLANOX_PLATFORM n
SURFACE_PLATFORMS n
HAVE_CLK y
HAVE_CLK_PREPARE y
COMMON_CLK y

#
# Clock driver for ARM Reference designs
#
ICST n
CLK_SP810 n
# end of Clock driver for ARM Reference designs

XILINX_VCU n
HWSPINLOCK n

#
# Clock Source drivers
#
CLKEVT_I8253 y
I8253_LOCK y
CLKBLD_I8253 y
# end of Clock Source drivers

MAILBOX y
PCC y
ALTERA_MBOX n
IOMMU_IOVA y
IOMMU_API y
IOMMU_SUPPORT y

#
# Generic IOMMU Pagetable Support
#
# end of Generic IOMMU Pagetable Support

IOMMU_DEBUGFS n
IOMMU_DEFAULT_DMA_STRICT n
IOMMU_DEFAULT_DMA_LAZY y
IOMMU_DEFAULT_PASSTHROUGH n
IOMMU_DMA y
AMD_IOMMU n
INTEL_IOMMU n
IRQ_REMAP n
HYPERV_IOMMU y
VIRTIO_IOMMU y

#
# Remoteproc drivers
#
REMOTEPROC n
# end of Remoteproc drivers

#
# Rpmsg drivers
#
RPMSG_QCOM_GLINK_RPM n
RPMSG_VIRTIO n
# end of Rpmsg drivers

SOUNDWIRE n

#
# SOC (System On Chip) specific Drivers
#

#
# Amlogic SoC drivers
#
# end of Amlogic SoC drivers

#
# Broadcom SoC drivers
#
# end of Broadcom SoC drivers

#
# NXP/Freescale QorIQ SoC drivers
#
# end of NXP/Freescale QorIQ SoC drivers

#
# i.MX SoC drivers
#
# end of i.MX SoC drivers

#
# Enable LiteX SoC Builder specific drivers
#
# end of Enable LiteX SoC Builder specific drivers

#
# Qualcomm SoC drivers
#
# end of Qualcomm SoC drivers

SOC_TI n

#
# Xilinx SoC drivers
#
# end of Xilinx SoC drivers
# end of SOC (System On Chip) specific Drivers

PM_DEVFREQ n
EXTCON n
MEMORY n
IIO n
NTB n
VME_BUS n
PWM n

#
# IRQ chip support
#
# end of IRQ chip support

IPACK_BUS n
RESET_CONTROLLER n

#
# PHY Subsystem
#
GENERIC_PHY n
PHY_CAN_TRANSCEIVER n
BCM_KONA_USB2_PHY n
PHY_PXA_28NM_HSIC n
PHY_PXA_28NM_USB2 n
PHY_INTEL_LGM_EMMC n
# end of PHY Subsystem

POWERCAP n
MCB n

#
# Performance monitor support
#
# end of Performance monitor support

RAS y
USB4 n

#
# Android
#
ANDROID n
# end of Android

LIBNVDIMM y
BLK_DEV_PMEM y
ND_BLK y
ND_CLAIM y
ND_BTT y
BTT y
ND_PFN y
NVDIMM_PFN y
NVDIMM_DAX y
DAX_DRIVER y
DAX y
DEV_DAX n
NVMEM n

#
# HW tracing support
#
STM n
INTEL_TH n
# end of HW tracing support

FPGA n
TEE n
UNISYS_VISORBUS n
SIOX n
SLIMBUS n
INTERCONNECT n
COUNTER n
MOST n
# end of Device Drivers

#
# File systems
#
DCACHE_WORD_ACCESS y
VALIDATE_FS_PARSER n
FS_IOMAP y
EXT2_FS n
EXT3_FS n
EXT4_FS y
EXT4_USE_FOR_EXT2 y
EXT4_FS_POSIX_ACL y
EXT4_FS_SECURITY y
EXT4_DEBUG y
JBD2 y
JBD2_DEBUG y
FS_MBCACHE y
REISERFS_FS n
JFS_FS n
XFS_FS n
GFS2_FS n
OCFS2_FS n
BTRFS_FS n
NILFS2_FS n
F2FS_FS n
FS_DAX y
FS_DAX_PMD y
FS_POSIX_ACL y
EXPORTFS y
EXPORTFS_BLOCK_OPS n
FILE_LOCKING y
FS_ENCRYPTION y
FS_ENCRYPTION_ALGS y
FS_VERITY n
FSNOTIFY y
DNOTIFY y
INOTIFY_USER y
FANOTIFY y
QUOTA n
AUTOFS4_FS y
AUTOFS_FS y
FUSE_FS y
CUSE y
VIRTIO_FS y
FUSE_DAX y
OVERLAY_FS y
OVERLAY_FS_REDIRECT_DIR n
OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW y
OVERLAY_FS_INDEX n
OVERLAY_FS_XINO_AUTO n
OVERLAY_FS_METACOPY n

#
# Caches
#
NETFS_SUPPORT y
NETFS_STATS n
FSCACHE y
FSCACHE_STATS n
FSCACHE_DEBUG n
CACHEFILES y
CACHEFILES_DEBUG n
# end of Caches

#
# CD-ROM/DVD Filesystems
#
ISO9660_FS n
UDF_FS n
# end of CD-ROM/DVD Filesystems

#
# DOS/FAT/EXFAT/NT Filesystems
#
FAT_FS y
MSDOS_FS y
VFAT_FS y
FAT_DEFAULT_CODEPAGE 437
FAT_DEFAULT_IOCHARSET "ascii"
FAT_DEFAULT_UTF8 n
EXFAT_FS n
NTFS_FS n
NTFS3_FS n
# end of DOS/FAT/EXFAT/NT Filesystems

#
# Pseudo filesystems
#
PROC_FS y
PROC_KCORE y
PROC_SYSCTL y
PROC_PAGE_MONITOR y
PROC_CHILDREN y
PROC_PID_ARCH_STATUS y
KERNFS y
SYSFS y
TMPFS y
TMPFS_POSIX_ACL y
TMPFS_XATTR y
TMPFS_INODE64 n
HUGETLBFS y
HUGETLB_PAGE y
HUGETLB_PAGE_FREE_VMEMMAP y
HUGETLB_PAGE_FREE_VMEMMAP_DEFAULT_ON n
MEMFD_CREATE y
ARCH_HAS_GIGANTIC_PAGE y
CONFIGFS_FS y
EFIVAR_FS y
# end of Pseudo filesystems

MISC_FILESYSTEMS n
NETWORK_FILESYSTEMS n
NLS y
NLS_DEFAULT "utf8"
NLS_CODEPAGE_437 y
NLS_CODEPAGE_737 y
NLS_CODEPAGE_775 y
NLS_CODEPAGE_850 y
NLS_CODEPAGE_852 y
NLS_CODEPAGE_855 y
NLS_CODEPAGE_857 y
NLS_CODEPAGE_860 y
NLS_CODEPAGE_861 y
NLS_CODEPAGE_862 y
NLS_CODEPAGE_863 y
NLS_CODEPAGE_864 y
NLS_CODEPAGE_865 y
NLS_CODEPAGE_866 y
NLS_CODEPAGE_869 y
NLS_CODEPAGE_936 y
NLS_CODEPAGE_950 y
NLS_CODEPAGE_932 y
NLS_CODEPAGE_949 y
NLS_CODEPAGE_874 y
NLS_ISO8859_8 y
NLS_CODEPAGE_1250 y
NLS_CODEPAGE_1251 y
NLS_ASCII y
NLS_ISO8859_1 y
NLS_ISO8859_2 y
NLS_ISO8859_3 y
NLS_ISO8859_4 y
NLS_ISO8859_5 y
NLS_ISO8859_6 y
NLS_ISO8859_7 y
NLS_ISO8859_9 y
NLS_ISO8859_13 y
NLS_ISO8859_14 y
NLS_ISO8859_15 y
NLS_KOI8_R y
NLS_KOI8_U y
NLS_MAC_ROMAN y
NLS_MAC_CELTIC y
NLS_MAC_CENTEURO y
NLS_MAC_CROATIAN y
NLS_MAC_CYRILLIC y
NLS_MAC_GAELIC y
NLS_MAC_GREEK y
NLS_MAC_ICELAND y
NLS_MAC_INUIT y
NLS_MAC_ROMANIAN y
NLS_MAC_TURKISH y
NLS_UTF8 y
DLM n
UNICODE n
IO_WQ y
# end of File systems

#
# Security options
#
KEYS y
KEYS_REQUEST_CACHE n
PERSISTENT_KEYRINGS y
ENCRYPTED_KEYS n
KEY_DH_OPERATIONS n
SECURITY_DMESG_RESTRICT n
SECURITY n
SECURITYFS y
PAGE_TABLE_ISOLATION y
HAVE_HARDENED_USERCOPY_ALLOCATOR y
HARDENED_USERCOPY n
FORTIFY_SOURCE y
STATIC_USERMODEHELPER n
IMA_SECURE_AND_OR_TRUSTED_BOOT n
DEFAULT_SECURITY_DAC y
LSM "yama,loadpin,safesetid,integrity"

#
# Kernel hardening options
#

#
# Memory initialization
#
INIT_STACK_NONE y
INIT_ON_ALLOC_DEFAULT_ON n
INIT_ON_FREE_DEFAULT_ON n
CC_HAS_ZERO_CALL_USED_REGS y
# end of Memory initialization
# end of Kernel hardening options
# end of Security options

CRYPTO y

#
# Crypto core or helper
#
CRYPTO_FIPS n
CRYPTO_ALGAPI y
CRYPTO_ALGAPI2 y
CRYPTO_AEAD y
CRYPTO_AEAD2 y
CRYPTO_SKCIPHER y
CRYPTO_SKCIPHER2 y
CRYPTO_HASH y
CRYPTO_HASH2 y
CRYPTO_RNG y
CRYPTO_RNG2 y
CRYPTO_RNG_DEFAULT y
CRYPTO_AKCIPHER2 y
CRYPTO_KPP2 y
CRYPTO_ACOMP2 y
CRYPTO_MANAGER y
CRYPTO_MANAGER2 y
CRYPTO_USER n
CRYPTO_MANAGER_DISABLE_TESTS n
CRYPTO_MANAGER_EXTRA_TESTS n
CRYPTO_GF128MUL y
CRYPTO_NULL y
CRYPTO_NULL2 y
CRYPTO_PCRYPT n
CRYPTO_CRYPTD y
CRYPTO_AUTHENC n
CRYPTO_TEST n
CRYPTO_SIMD y

#
# Public-key cryptography
#
CRYPTO_RSA n
CRYPTO_DH n
CRYPTO_ECDH n
CRYPTO_ECDSA n
CRYPTO_ECRDSA n
CRYPTO_SM2 n
CRYPTO_CURVE25519 n
CRYPTO_CURVE25519_X86 n

#
# Authenticated Encryption with Associated Data
#
CRYPTO_CCM n
CRYPTO_GCM y
CRYPTO_CHACHA20POLY1305 n
CRYPTO_AEGIS128 n
CRYPTO_AEGIS128_AESNI_SSE2 n
CRYPTO_SEQIV y
CRYPTO_ECHAINIV y

#
# Block modes
#
CRYPTO_CBC y
CRYPTO_CFB n
CRYPTO_CTR y
CRYPTO_CTS y
CRYPTO_ECB y
CRYPTO_LRW y
CRYPTO_OFB n
CRYPTO_PCBC y
CRYPTO_XTS y
CRYPTO_KEYWRAP n
CRYPTO_NHPOLY1305_SSE2 n
CRYPTO_NHPOLY1305_AVX2 n
CRYPTO_ADIANTUM n
CRYPTO_ESSIV n

#
# Hash modes
#
CRYPTO_CMAC y
CRYPTO_HMAC y
CRYPTO_XCBC n
CRYPTO_VMAC n

#
# Digest
#
CRYPTO_CRC32C y
CRYPTO_CRC32C_INTEL y
CRYPTO_CRC32 n
CRYPTO_CRC32_PCLMUL n
CRYPTO_XXHASH n
CRYPTO_BLAKE2B n
CRYPTO_BLAKE2S n
CRYPTO_BLAKE2S_X86 n
CRYPTO_CRCT10DIF y
CRYPTO_CRCT10DIF_PCLMUL n
CRYPTO_GHASH y
CRYPTO_POLY1305 y
CRYPTO_POLY1305_X86_64 n
CRYPTO_MD4 n
CRYPTO_MD5 y
CRYPTO_MICHAEL_MIC n
CRYPTO_RMD160 n
CRYPTO_SHA1 n
CRYPTO_SHA1_SSSE3 n
CRYPTO_SHA256_SSSE3 n
CRYPTO_SHA512_SSSE3 n
CRYPTO_SHA256 y
CRYPTO_SHA512 y
CRYPTO_SHA3 n
CRYPTO_SM3 n
CRYPTO_STREEBOG n
CRYPTO_WP512 n
CRYPTO_GHASH_CLMUL_NI_INTEL n

#
# Ciphers
#
CRYPTO_AES y
CRYPTO_AES_TI n
CRYPTO_AES_NI_INTEL y
CRYPTO_BLOWFISH n
CRYPTO_BLOWFISH_X86_64 n
CRYPTO_CAMELLIA n
CRYPTO_CAMELLIA_X86_64 n
CRYPTO_CAMELLIA_AESNI_AVX_X86_64 n
CRYPTO_CAMELLIA_AESNI_AVX2_X86_64 n
CRYPTO_CAST5 n
CRYPTO_CAST5_AVX_X86_64 n
CRYPTO_CAST6 n
CRYPTO_CAST6_AVX_X86_64 n
CRYPTO_DES y
CRYPTO_DES3_EDE_X86_64 n
CRYPTO_FCRYPT n
CRYPTO_CHACHA20 n
CRYPTO_CHACHA20_X86_64 n
CRYPTO_SERPENT n
CRYPTO_SERPENT_SSE2_X86_64 n
CRYPTO_SERPENT_AVX_X86_64 n
CRYPTO_SERPENT_AVX2_X86_64 n
CRYPTO_SM4 n
CRYPTO_SM4_AESNI_AVX_X86_64 n
CRYPTO_SM4_AESNI_AVX2_X86_64 n
CRYPTO_TWOFISH n
CRYPTO_TWOFISH_COMMON y
CRYPTO_TWOFISH_X86_64 y
CRYPTO_TWOFISH_X86_64_3WAY y
CRYPTO_TWOFISH_AVX_X86_64 y

#
# Compression
#
CRYPTO_DEFLATE y
CRYPTO_LZO y
CRYPTO_842 n
CRYPTO_LZ4 n
CRYPTO_LZ4HC n
CRYPTO_ZSTD n

#
# Random Number Generation
#
CRYPTO_ANSI_CPRNG n
CRYPTO_DRBG_MENU y
CRYPTO_DRBG_HMAC y
CRYPTO_DRBG_HASH y
CRYPTO_DRBG_CTR y
CRYPTO_DRBG y
CRYPTO_JITTERENTROPY y
CRYPTO_USER_API y
CRYPTO_USER_API_HASH n
CRYPTO_USER_API_SKCIPHER n
CRYPTO_USER_API_RNG y
CRYPTO_USER_API_RNG_CAVP n
CRYPTO_USER_API_AEAD n
CRYPTO_USER_API_ENABLE_OBSOLETE n

#
# Crypto library routines
#
CRYPTO_LIB_AES y
CRYPTO_LIB_BLAKE2S n
CRYPTO_LIB_CHACHA n
CRYPTO_LIB_CURVE25519 n
CRYPTO_LIB_DES y
CRYPTO_LIB_POLY1305_RSIZE 11
CRYPTO_LIB_POLY1305_GENERIC y
CRYPTO_LIB_POLY1305 n
CRYPTO_LIB_CHACHA20POLY1305 n
CRYPTO_LIB_SHA256 y
CRYPTO_HW n
ASYMMETRIC_KEY_TYPE n

#
# Certificates for signature checking
#
SYSTEM_BLACKLIST_KEYRING y
SYSTEM_BLACKLIST_HASH_LIST ""
# end of Certificates for signature checking

BINARY_PRINTF y

#
# Library routines
#
PACKING n
BITREVERSE y
GENERIC_STRNCPY_FROM_USER y
GENERIC_STRNLEN_USER y
GENERIC_NET_UTILS y
GENERIC_FIND_FIRST_BIT y
CORDIC n
PRIME_NUMBERS n
RATIONAL y
GENERIC_PCI_IOMAP y
GENERIC_IOMAP y
ARCH_USE_CMPXCHG_LOCKREF y
ARCH_HAS_FAST_MULTIPLIER y
ARCH_USE_SYM_ANNOTATIONS y
CRC_CCITT y
CRC16 y
CRC_T10DIF y
CRC_ITU_T n
CRC32 y
CRC32_SELFTEST n
CRC32_SLICEBY8 y
CRC32_SLICEBY4 n
CRC32_SARWATE n
CRC32_BIT n
CRC64 n
CRC4 n
CRC7 n
LIBCRC32C y
CRC8 n
XXHASH y
RANDOM32_SELFTEST n
ZLIB_INFLATE y
ZLIB_DEFLATE y
LZO_COMPRESS y
LZO_DECOMPRESS y
LZ4_DECOMPRESS y
ZSTD_DECOMPRESS y
XZ_DEC y
XZ_DEC_X86 y
XZ_DEC_POWERPC y
XZ_DEC_IA64 y
XZ_DEC_ARM y
XZ_DEC_ARMTHUMB y
XZ_DEC_SPARC y
XZ_DEC_BCJ y
XZ_DEC_TEST n
DECOMPRESS_GZIP y
DECOMPRESS_BZIP2 y
DECOMPRESS_LZMA y
DECOMPRESS_XZ y
DECOMPRESS_LZO y
DECOMPRESS_LZ4 y
DECOMPRESS_ZSTD y
GENERIC_ALLOCATOR y
INTERVAL_TREE y
XARRAY_MULTI y
ASSOCIATIVE_ARRAY y
HAS_IOMEM y
HAS_IOPORT_MAP y
HAS_DMA y
DMA_OPS y
NEED_SG_DMA_LENGTH y
NEED_DMA_MAP_STATE y
ARCH_DMA_ADDR_T_64BIT y
ARCH_HAS_FORCE_DMA_UNENCRYPTED y
SWIOTLB y
DMA_COHERENT_POOL y
DMA_API_DEBUG n
DMA_MAP_BENCHMARK n
SGL_ALLOC y
CPU_RMAP y
DQL y
NLATTR y
IRQ_POLL y
UCS2_STRING y
HAVE_GENERIC_VDSO y
GENERIC_GETTIMEOFDAY y
GENERIC_VDSO_TIME_NS y
FONT_SUPPORT y
FONTS n
FONT_8x8 y
FONT_8x16 y
ARCH_HAS_PMEM_API y
MEMREGION y
ARCH_HAS_UACCESS_FLUSHCACHE y
ARCH_HAS_COPY_MC y
ARCH_STACKWALK y
SBITMAP y
# end of Library routines

#
# Kernel hacking
#

#
# printk and dmesg options
#
PRINTK_TIME y
PRINTK_CALLER n
STACKTRACE_BUILD_ID n
CONSOLE_LOGLEVEL_DEFAULT 7
CONSOLE_LOGLEVEL_QUIET 4
MESSAGE_LOGLEVEL_DEFAULT 4
BOOT_PRINTK_DELAY n
DYNAMIC_DEBUG y
DYNAMIC_DEBUG_CORE y
SYMBOLIC_ERRNAME y
DEBUG_BUGVERBOSE n
# end of printk and dmesg options

#
# Compile-time checks and compiler options
#
DEBUG_INFO n
FRAME_WARN 2048
STRIP_ASM_SYMS y
READABLE_ASM n
HEADERS_INSTALL n
DEBUG_SECTION_MISMATCH y
SECTION_MISMATCH_WARN_ONLY y
DEBUG_FORCE_FUNCTION_ALIGN_64B n
FRAME_POINTER y
STACK_VALIDATION y
VMLINUX_MAP n
DEBUG_FORCE_WEAK_PER_CPU n
# end of Compile-time checks and compiler options

#
# Generic Kernel Debugging Instruments
#
MAGIC_SYSRQ y
MAGIC_SYSRQ_DEFAULT_ENABLE 0x1
MAGIC_SYSRQ_SERIAL y
MAGIC_SYSRQ_SERIAL_SEQUENCE ""
DEBUG_FS y
DEBUG_FS_ALLOW_ALL y
DEBUG_FS_DISALLOW_MOUNT n
DEBUG_FS_ALLOW_NONE n
HAVE_ARCH_KGDB y
KGDB n
ARCH_HAS_UBSAN_SANITIZE_ALL y
UBSAN n
HAVE_ARCH_KCSAN y
HAVE_KCSAN_COMPILER y
KCSAN n
# end of Generic Kernel Debugging Instruments

DEBUG_KERNEL y
DEBUG_MISC y

#
# Memory Debugging
#
PAGE_EXTENSION n
DEBUG_PAGEALLOC n
PAGE_OWNER n
PAGE_POISONING n
DEBUG_RODATA_TEST n
ARCH_HAS_DEBUG_WX y
DEBUG_WX n
GENERIC_PTDUMP y
PTDUMP_DEBUGFS n
DEBUG_OBJECTS n
SLUB_DEBUG_ON n
SLUB_STATS n
HAVE_DEBUG_KMEMLEAK y
DEBUG_KMEMLEAK n
DEBUG_STACK_USAGE n
SCHED_STACK_END_CHECK n
ARCH_HAS_DEBUG_VM_PGTABLE y
DEBUG_VM n
DEBUG_VM_PGTABLE n
ARCH_HAS_DEBUG_VIRTUAL y
DEBUG_VIRTUAL n
DEBUG_MEMORY_INIT y
DEBUG_PER_CPU_MAPS n
ARCH_SUPPORTS_KMAP_LOCAL_FORCE_MAP y
DEBUG_KMAP_LOCAL_FORCE_MAP n
HAVE_ARCH_KASAN y
HAVE_ARCH_KASAN_VMALLOC y
CC_HAS_KASAN_GENERIC y
CC_HAS_WORKING_NOSANITIZE_ADDRESS y
KASAN n
HAVE_ARCH_KFENCE y
KFENCE n
# end of Memory Debugging

DEBUG_SHIRQ n

#
# Debug Oops, Lockups and Hangs
#
PANIC_ON_OOPS n
PANIC_ON_OOPS_VALUE 0
PANIC_TIMEOUT 0
SOFTLOCKUP_DETECTOR n
HARDLOCKUP_CHECK_TIMESTAMP y
HARDLOCKUP_DETECTOR n
DETECT_HUNG_TASK n
WQ_WATCHDOG n
# end of Debug Oops, Lockups and Hangs

#
# Scheduler Debugging
#
SCHED_DEBUG n
SCHED_INFO y
SCHEDSTATS n
# end of Scheduler Debugging

DEBUG_TIMEKEEPING n

#
# Lock Debugging (spinlocks, mutexes, etc...)
#
LOCK_DEBUGGING_SUPPORT y
PROVE_LOCKING n
LOCK_STAT n
DEBUG_RT_MUTEXES n
DEBUG_SPINLOCK n
DEBUG_MUTEXES n
DEBUG_WW_MUTEX_SLOWPATH n
DEBUG_RWSEMS n
DEBUG_LOCK_ALLOC n
DEBUG_ATOMIC_SLEEP n
DEBUG_LOCKING_API_SELFTESTS n
LOCK_TORTURE_TEST n
WW_MUTEX_SELFTEST n
SCF_TORTURE_TEST n
CSD_LOCK_WAIT_DEBUG n
# end of Lock Debugging (spinlocks, mutexes, etc...)

DEBUG_IRQFLAGS n
STACKTRACE y
WARN_ALL_UNSEEDED_RANDOM n
DEBUG_KOBJECT n

#
# Debug kernel data structures
#
DEBUG_LIST y
DEBUG_PLIST n
DEBUG_SG n
DEBUG_NOTIFIERS n
BUG_ON_DATA_CORRUPTION y
# end of Debug kernel data structures

DEBUG_CREDENTIALS n

#
# RCU Debugging
#
RCU_SCALE_TEST n
RCU_TORTURE_TEST n
RCU_REF_SCALE_TEST n
RCU_CPU_STALL_TIMEOUT 59
RCU_TRACE n
RCU_EQS_DEBUG n
# end of RCU Debugging

DEBUG_WQ_FORCE_RR_CPU n
CPU_HOTPLUG_STATE_CONTROL n
LATENCYTOP n
USER_STACKTRACE_SUPPORT y
HAVE_FUNCTION_TRACER y
HAVE_FUNCTION_GRAPH_TRACER y
HAVE_DYNAMIC_FTRACE y
HAVE_DYNAMIC_FTRACE_WITH_REGS y
HAVE_DYNAMIC_FTRACE_WITH_DIRECT_CALLS y
HAVE_DYNAMIC_FTRACE_WITH_ARGS y
HAVE_FTRACE_MCOUNT_RECORD y
HAVE_SYSCALL_TRACEPOINTS y
HAVE_FENTRY y
HAVE_OBJTOOL_MCOUNT y
HAVE_C_RECORDMCOUNT y
TRACING_SUPPORT y
FTRACE n
PROVIDE_OHCI1394_DMA_INIT n
SAMPLES n
ARCH_HAS_DEVMEM_IS_ALLOWED y
STRICT_DEVMEM y
IO_STRICT_DEVMEM n

#
# x86 Debugging
#
TRACE_IRQFLAGS_NMI_SUPPORT y
X86_VERBOSE_BOOTUP y
EARLY_PRINTK y
EARLY_PRINTK_DBGP n
EARLY_PRINTK_USB_XDBC n
EFI_PGT_DUMP n
DEBUG_TLBFLUSH n
HAVE_MMIOTRACE_SUPPORT y
X86_DECODER_SELFTEST n
IO_DELAY_0X80 y
IO_DELAY_0XED n
IO_DELAY_UDELAY n
IO_DELAY_NONE n
DEBUG_BOOT_PARAMS n
CPA_DEBUG n
DEBUG_ENTRY n
DEBUG_NMI_SELFTEST n
X86_DEBUG_FPU n
PUNIT_ATOM_DEBUG n
UNWINDER_ORC n
UNWINDER_FRAME_POINTER y
UNWINDER_GUESS n
# end of x86 Debugging

#
# Kernel Testing and Coverage
#
KUNIT n
NOTIFIER_ERROR_INJECTION n
FAULT_INJECTION n
ARCH_HAS_KCOV y
CC_HAS_SANCOV_TRACE_PC y
KCOV n
RUNTIME_TESTING_MENU y
LKDTM n
TEST_MIN_HEAP n
TEST_DIV64 n
BACKTRACE_SELF_TEST n
RBTREE_TEST n
REED_SOLOMON_TEST n
INTERVAL_TREE_TEST n
ATOMIC64_SELFTEST n
TEST_HEXDUMP n
STRING_SELFTEST n
TEST_STRING_HELPERS n
TEST_STRSCPY n
TEST_KSTRTOX n
TEST_PRINTF n
TEST_SCANF n
TEST_BITMAP n
TEST_UUID n
TEST_XARRAY n
TEST_OVERFLOW n
TEST_RHASHTABLE n
TEST_HASH n
TEST_IDA n
FIND_BIT_BENCHMARK n
TEST_FIRMWARE n
TEST_SYSCTL n
TEST_UDELAY n
TEST_MEMCAT_P n
TEST_STACKINIT n
TEST_MEMINIT n
TEST_FREE_PAGES n
TEST_FPU n
TEST_CLOCKSOURCE_WATCHDOG n
ARCH_USE_MEMTEST y
MEMTEST n
HYPERV_TESTING n
# end of Kernel Testing and Coverage
# end of Kernel hacking
  '';
}
