plugin_dirs = [
    '/home/jan/.local/share/wineprefixes/wine-vst64/drive_c/Program Files/Common Files/VST2',
    '/home/jan/.local/share/wineprefixes/wine-vst64/drive_c/Program Files/Common Files/VST3',
]
vst2_location = 'centralized'
no_verify = false
blacklist = []
